services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qrcodescan_bot
    environment:
      - BOT_TOKEN=7808674035:AAGUmYxc__b5hUxy4hA6cM_K01UI9RvHIpA
    volumes:
      - ./data:/app/data  # Ma'lumotlarni saqlash uchun jild
    restart: unless-stopped  # Konteyner o'chganda avto-qayta ishga tushadi

volumes:
  data:  # Ma'lumotlarni saqlash uchun nomlangan jild